### ISSUE TITLE
RubyML list

### ISSUE THREAD

**Issue by arbox** [thoughtfulml/examples#6]
Dear Matt,

I've recently added your project to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

I wonder if you want to participate in the Ruby for ML network. You could do this in a very simple step by adding the `rubyml` topic to your GitHub repository. And you may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by hexgnu** [comment]
done thanks! @arbox
